# Generated by Django 5.2.5 on 2025-09-27 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0011_remove_persona_estecnico_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Sub Unidad')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='SubUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Sub Unidad')),
                ('direccion', models.CharField(blank=True, max_length=70, null=True, verbose_name='Dirección')),
                ('telefono_contacto', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono de contacto.')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicacion.unidad')),
            ],
            options={
                'verbose_name': 'Sub Unidad',
                'verbose_name_plural': 'Sub Unidades',
            },
        ),
    ]
