# Generated by Django 5.2 on 2025-08-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subunidad',
            name='direccion',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Dirección'),
        ),
    ]
