# Generated by Django 5.2.5 on 2025-09-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subunidad',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Sub Unidad'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Sub Unidad'),
        ),
    ]
