# Generated by Django 5.2.5 on 2025-08-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0002_alter_subunidad_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subunidad',
            name='telefono_contacto',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
