# Generated by Django 5.2.5 on 2025-09-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0003_alter_subunidad_telefono_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subunidad',
            name='telefono_contacto',
            field=models.CharField(blank=True, null=True, verbose_name='Teléfono de contacto.'),
        ),
    ]
