# Generated by Django 5.1.5 on 2025-01-20 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=None, max_length=12)),
                ('nombre', models.CharField(blank=None, max_length=100)),
                ('telefono', models.CharField(blank=None, max_length=12)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grado.grado')),
            ],
        ),
    ]
