# Generated by Django 5.1.5 on 2025-01-20 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_persona_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.persona')),
                ('especialidad', models.CharField(max_length=500)),
            ],
            bases=('persona.persona',),
        ),
    ]
