# Generated by Django 5.1.5 on 2025-01-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estecnico',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Tecnico',
        ),
    ]
