# Generated by Django 5.1.5 on 2025-01-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_persona_estecnico_delete_tecnico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='estecnico',
            new_name='Es Tecnico?',
        ),
    ]
