# Generated by Django 5.1.5 on 2025-01-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_alter_persona_codigo_alter_persona_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='Es Tecnico?',
            new_name='estecnico',
        ),
    ]
