# Generated by Django 5.1.5 on 2025-01-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_alter_persona_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.IntegerField(max_length=12),
        ),
    ]
