# Generated by Django 5.1.5 on 2025-02-04 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grado', '0002_alter_grado_nombre'),
        ('persona', '0010_alter_persona_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='estecnico',
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
                ('created', models.DateTimeField(auto_now=True)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grado.grado')),
            ],
        ),
    ]
