# Generated by Django 5.2.5 on 2025-09-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidadoTDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('start_page', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DescripcionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_servicio', models.TextField()),
            ],
            options={
                'verbose_name': 'Descripción de Servicio (Catálogo)',
                'verbose_name_plural': 'Descripciones de Servicio (Catálogo)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación del TDR')),
                ('informe_tecnico_nro', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nº Informe Técnico')),
            ],
            options={
                'verbose_name': 'Requerimiento TDR',
                'verbose_name_plural': 'Requerimientos TDRs',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RequerimientoDescripcionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Detalle de Servicio del Requerimiento',
                'verbose_name_plural': 'Detalles de Servicios del Requerimiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RequerimientoPiezaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Propuesta')),
            ],
            options={
                'verbose_name': 'Detalle de Pieza del Requerimiento',
                'verbose_name_plural': 'Detalles de Piezas del Requerimiento',
                'ordering': ['id'],
            },
        ),
    ]
