# Generated by Django 5.2 on 2025-08-14 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pieza', '0004_alter_pieza_cantidad_stock_alter_pieza_nombre_and_more'),
        ('ubicacion', '0002_alter_subunidad_direccion'),
        ('vehiculo', '0014_alter_vehiculo_placa_int_alter_vehiculo_placa_rod'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_servicio', models.TextField(unique=True, verbose_name='Descripción del Servicio Propuesto')),
            ],
            options={
                'verbose_name': 'Descripción de Servicio (TDR)',
                'verbose_name_plural': 'Descripciones de Servicio (TDR)',
            },
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del TDR')),
                ('informe_tecnico_nro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Informe Técnico')),
                ('comisaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion.unidad', verbose_name='Comisaría Asignada')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo', verbose_name='Vehículo del Requerimiento')),
            ],
            options={
                'verbose_name': 'Requerimiento TDR',
                'verbose_name_plural': 'Requerimientos TDRs',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RequerimientoDescripcionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones de la Tarea')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdr.descripcionservicio', verbose_name='Descripción del Servicio Propuesto')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdr.requerimiento', verbose_name='Requerimiento Asociado')),
            ],
            options={
                'verbose_name': 'Detalle de Servicio del Requerimiento',
                'verbose_name_plural': 'Detalles de Servicios del Requerimiento',
                'unique_together': {('requerimiento', 'detalle')},
            },
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='servicios_propuestos',
            field=models.ManyToManyField(related_name='requerimientos_asociados_servicio', through='tdr.RequerimientoDescripcionDetalle', to='tdr.descripcionservicio', verbose_name='Servicios Propuestos en TDR'),
        ),
        migrations.CreateModel(
            name='RequerimientoPiezaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Propuesta')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pieza.pieza', verbose_name='Pieza Propuesta')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdr.requerimiento', verbose_name='Requerimiento Asociado')),
            ],
            options={
                'verbose_name': 'Detalle de Pieza del Requerimiento',
                'verbose_name_plural': 'Detalles de Piezas del Requerimiento',
                'unique_together': {('requerimiento', 'pieza')},
            },
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='piezas_propuestas',
            field=models.ManyToManyField(related_name='requerimientos_asociados_pieza', through='tdr.RequerimientoPiezaDetalle', to='pieza.pieza', verbose_name='Piezas Propuestas en TDR'),
        ),
    ]
