# Generated by Django 5.2 on 2025-08-17 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pieza', '0004_alter_pieza_cantidad_stock_alter_pieza_nombre_and_more'),
        ('vehiculo', '0016_alter_vehiculo_estado_odo_alter_vehiculo_estado_vehi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_servicio', models.TextField(unique=True, verbose_name='Descripción del Servicio')),
            ],
            options={
                'verbose_name': 'Descripción de Servicio (Catálogo)',
                'verbose_name_plural': 'Descripciones de Servicio (Catálogo)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación del TDR')),
                ('informe_tecnico_nro', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nº Informe Técnico')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos', to='vehiculo.vehiculo', verbose_name='Vehículo del Requerimiento')),
            ],
            options={
                'verbose_name': 'Requerimiento TDR',
                'verbose_name_plural': 'Requerimientos TDRs',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RequerimientoDescripcionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='en_requerimientos_detalle', to='tdr.descripcionservicio', verbose_name='Descripción del Servicio Propuesto')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio', to='tdr.requerimiento', verbose_name='Requerimiento Asociado')),
            ],
            options={
                'verbose_name': 'Detalle de Servicio del Requerimiento',
                'verbose_name_plural': 'Detalles de Servicios del Requerimiento',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='servicios_propuestos',
            field=models.ManyToManyField(related_name='requerimientos_asociados_servicio', through='tdr.RequerimientoDescripcionDetalle', to='tdr.descripcionservicio', verbose_name='Servicios Propuestos en TDR'),
        ),
        migrations.CreateModel(
            name='RequerimientoPiezaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Propuesta')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_requerimientos_piezas', to='pieza.pieza', verbose_name='Pieza Propuesta')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pieza', to='tdr.requerimiento', verbose_name='Requerimiento Asociado')),
            ],
            options={
                'verbose_name': 'Detalle de Pieza del Requerimiento',
                'verbose_name_plural': 'Detalles de Piezas del Requerimiento',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='piezas_propuestas',
            field=models.ManyToManyField(related_name='en_requerimientos', through='tdr.RequerimientoPiezaDetalle', to='pieza.pieza', verbose_name='Piezas Propuestas en TDR'),
        ),
        migrations.AddConstraint(
            model_name='requerimientodescripciondetalle',
            constraint=models.UniqueConstraint(fields=('requerimiento', 'detalle'), name='uniq_req_detalle'),
        ),
        migrations.AddConstraint(
            model_name='requerimientopiezadetalle',
            constraint=models.UniqueConstraint(fields=('requerimiento', 'pieza'), name='uniq_req_pieza'),
        ),
    ]
