# Generated by Django 5.2 on 2025-08-14 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdr', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requerimientodescripciondetalle',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='requerimientodescripciondetalle',
            name='detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tdr.descripcionservicio', verbose_name='Descripción del Servicio Propuesto'),
        ),
        migrations.RemoveField(
            model_name='requerimientodescripciondetalle',
            name='observaciones',
        ),
    ]
