# Generated by Django 5.2.5 on 2025-09-01 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieza', '0005_piezatdr'),
        ('tdr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='requerimientodescripciondetalle',
            name='uniq_req_detalle',
        ),
        migrations.RemoveConstraint(
            model_name='requerimientopiezadetalle',
            name='uniq_req_pieza',
        ),
        migrations.RenameField(
            model_name='requerimientodescripciondetalle',
            old_name='detalle',
            new_name='detalle_servicio',
        ),
        migrations.RemoveField(
            model_name='requerimientopiezadetalle',
            name='pieza',
        ),
        migrations.AddField(
            model_name='requerimientopiezadetalle',
            name='detalle_pieza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='en_requerimientos_piezas', to='pieza.piezatdr', verbose_name='Pieza Propuesta'),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='piezas_propuestas',
            field=models.ManyToManyField(related_name='en_requerimientos', through='tdr.RequerimientoPiezaDetalle', to='pieza.piezatdr', verbose_name='Piezas Propuestas en TDR'),
        ),
        migrations.AddConstraint(
            model_name='requerimientodescripciondetalle',
            constraint=models.UniqueConstraint(fields=('requerimiento', 'detalle_servicio'), name='uniq_req_detalle'),
        ),
        migrations.AddConstraint(
            model_name='requerimientopiezadetalle',
            constraint=models.UniqueConstraint(fields=('requerimiento', 'detalle_pieza'), name='uniq_req_pieza'),
        ),
    ]
