# Generated by Django 5.2.5 on 2025-09-27 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pieza', '0001_initial'),
        ('tdr', '0001_initial'),
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos', to='vehiculo.vehiculo', verbose_name='Vehículo del Requerimiento'),
        ),
        migrations.AddField(
            model_name='consolidadotdr',
            name='tdrs',
            field=models.ManyToManyField(related_name='consolidados', to='tdr.requerimiento'),
        ),
        migrations.AddField(
            model_name='requerimientodescripciondetalle',
            name='detalle_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='en_requerimientos_detalle', to='tdr.descripcionservicio', verbose_name='Descripción del Servicio Propuesto'),
        ),
        migrations.AddField(
            model_name='requerimientodescripciondetalle',
            name='requerimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio', to='tdr.requerimiento', verbose_name='Requerimiento Asociado'),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='servicios_propuestos',
            field=models.ManyToManyField(related_name='requerimientos_asociados_servicio', through='tdr.RequerimientoDescripcionDetalle', to='tdr.descripcionservicio', verbose_name='Servicios Propuestos en TDR'),
        ),
        migrations.AddField(
            model_name='requerimientopiezadetalle',
            name='detalle_pieza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='en_requerimientos_piezas', to='pieza.piezatdr', verbose_name='Pieza Propuesta'),
        ),
        migrations.AddField(
            model_name='requerimientopiezadetalle',
            name='requerimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pieza', to='tdr.requerimiento', verbose_name='Requerimiento Asociado'),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='piezas_propuestas',
            field=models.ManyToManyField(related_name='en_requerimientos', through='tdr.RequerimientoPiezaDetalle', to='pieza.piezatdr', verbose_name='Piezas Propuestas en TDR'),
        ),
        migrations.AddConstraint(
            model_name='requerimientodescripciondetalle',
            constraint=models.UniqueConstraint(fields=('requerimiento', 'detalle_servicio'), name='uniq_req_detalle'),
        ),
        migrations.AddConstraint(
            model_name='requerimientopiezadetalle',
            constraint=models.UniqueConstraint(fields=('requerimiento', 'detalle_pieza'), name='uniq_req_pieza'),
        ),
    ]
