# Generated by Django 5.2 on 2025-08-14 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdr', '0002_alter_requerimientodescripciondetalle_unique_together_and_more'),
        ('ubicacion', '0002_alter_subunidad_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='comisaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion.subunidad', verbose_name='Comisaría Asignada'),
        ),
    ]
