# Generated by Django 5.2 on 2025-08-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdr', '0003_alter_requerimiento_comisaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requerimiento',
            name='comisaria',
        ),
    ]
