# Generated by Django 5.2.5 on 2025-09-10 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdr', '0003_consolidadotdr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolidadotdr',
            name='usuario',
        ),
    ]
