# Generated by Django 5.2 on 2025-08-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdr', '0004_remove_requerimiento_comisaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='informe_tecnico_nro',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nº Informe Técnico'),
        ),
    ]
