# Generated by Django 5.2.5 on 2025-09-27 05:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0011_remove_persona_estecnico_tecnico'),
        ('pieza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pieza.pieza')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('kilometraje_ant', models.DecimalField(decimal_places=1, max_digits=18)),
                ('kilometraje_act', models.DecimalField(decimal_places=1, max_digits=18)),
                ('kilometraje_diff', models.DecimalField(decimal_places=1, max_digits=18)),
                ('tipo', models.TextField(choices=[('CORRECTIVO', 'CORRECTIVO'), ('PREVENTIVO', 'PREVENTIVO')], default='Preventivo')),
                ('fecha_inicio', models.DateTimeField(default=datetime.datetime(2025, 9, 27, 0, 22, 40, 728092), editable=False)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado')], default='EN PROCESO', max_length=20)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.tecnico')),
            ],
        ),
    ]
