# Generated by Django 5.1.6 on 2025-02-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_servicio_kilomentraje_act_servicio_kilomentraje_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='kilomentraje_diff',
            field=models.IntegerField(default=0),
        ),
    ]
