# Generated by Django 5.2 on 2025-06-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0005_remove_servicio_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='kilometraje_act',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='kilometraje_diff',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
