# Generated by Django 5.2 on 2025-07-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_alter_movimientostock_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='tipo',
            field=models.TextField(choices=[('Correctivo', 'Correctivo'), ('Preventivo', 'Preventivo')], default='Preventivo'),
        ),
    ]
