# Generated by Django 5.2 on 2025-07-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0007_servicio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='kilometraje_ant',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
