# Generated by Django 5.2 on 2025-08-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0008_servicio_kilometraje_ant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='kilometraje_act',
            field=models.DecimalField(decimal_places=1, max_digits=18),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='kilometraje_ant',
            field=models.DecimalField(decimal_places=1, max_digits=18),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='kilometraje_diff',
            field=models.DecimalField(decimal_places=1, max_digits=18),
        ),
    ]
