# Generated by Django 5.2 on 2025-08-07 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0009_alter_servicio_kilometraje_act_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Aaddservicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio')),
                ('descripcion_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.descripcion_servicio')),
            ],
        ),
    ]
