# Generated by Django 5.2 on 2025-08-11 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0010_descripcion_servicio_aaddservicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aaddservicios',
            name='descripcion_servicio',
        ),
        migrations.RemoveField(
            model_name='aaddservicios',
            name='servicio',
        ),
        migrations.DeleteModel(
            name='Descripcion_Servicio',
        ),
        migrations.DeleteModel(
            name='Aaddservicios',
        ),
    ]
