# Generated by Django 5.2 on 2025-08-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0011_remove_aaddservicios_descripcion_servicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='fecha',
            new_name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
