# Generated by Django 5.2 on 2025-08-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0012_rename_fecha_servicio_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado')], default='EN_PROCESO', max_length=20),
        ),
    ]
