# Generated by Django 5.2 on 2025-08-11 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0013_servicio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('EN PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado')], default='EN PROCESO', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 11, 23, 15, 28, 620501), editable=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.TextField(choices=[('CORRECTIVO', 'CORRECTIVO'), ('PREVENTIVO', 'PREVENTIVO')], default='Preventivo'),
        ),
    ]
