# Generated by Django 5.2 on 2025-08-14 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0014_alter_servicio_estado_alter_servicio_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 14, 20, 48, 12, 506034), editable=False),
        ),
    ]
