# Generated by Django 5.2 on 2025-08-17 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0037_alter_servicio_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 1, 37, 17, 4602), editable=False),
        ),
    ]
