# Generated by Django 5.2.5 on 2025-09-11 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0044_alter_servicio_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 11, 11, 16, 40, 736756), editable=False),
        ),
    ]
