# Generated by Django 5.2.5 on 2025-09-23 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0046_alter_servicio_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 13, 36, 22, 719783), editable=False),
        ),
    ]
