# Generated by Django 5.2.5 on 2025-09-24 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0048_alter_servicio_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 24, 14, 26, 14, 400531), editable=False),
        ),
    ]
