# Generated by Django 5.2.5 on 2025-09-25 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0054_alter_servicio_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 25, 0, 11, 40, 521838), editable=False),
        ),
    ]
