# Generated by Django 5.2.5 on 2025-09-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cantidad_stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario', verbose_name='Stock actual')),
                ('reorder', models.PositiveIntegerField(default=0, help_text='Cantidad mínima antes de avisar stock bajo', verbose_name='Cantidad de aviso')),
            ],
        ),
        migrations.CreateModel(
            name='PiezaTDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_pieza', models.CharField(max_length=200, unique=True, verbose_name='Nombre Pieza')),
            ],
        ),
    ]
