# Generated by Django 5.1.5 on 2025-02-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pieza', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovimientoStock',
        ),
    ]
