# Generated by Django 5.1.6 on 2025-03-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pieza', '0002_delete_movimientostock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pieza',
            name='precio',
        ),
    ]
