# Generated by Django 5.2 on 2025-06-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieza', '0003_remove_pieza_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieza',
            name='cantidad_stock',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario', verbose_name='Stock actual'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='reorder',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad mínima antes de avisar stock bajo', verbose_name='Cantidad de aviso'),
        ),
    ]
