# Generated by Django 5.2.5 on 2025-09-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieza', '0004_alter_pieza_cantidad_stock_alter_pieza_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiezaTDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_pieza', models.CharField(unique=True, verbose_name='Nombre Pieza')),
            ],
        ),
    ]
