# Generated by Django 5.1.5 on 2025-01-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
