# Generated by Django 5.2.5 on 2025-09-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grado', '0003_alter_grado_options_grado_abreviatura_grado_orden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='orden',
            field=models.CharField(max_length=2, verbose_name='Orden Jerárquico'),
        ),
    ]
