# Generated by Django 5.1.5 on 2025-01-20 07:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=None, max_length=6)),
                ('marca', models.CharField(blank=None, max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField(blank=None)),
                ('kilometraje', models.IntegerField(blank=None)),
                ('created', models.DateTimeField(default=datetime.datetime(2025, 1, 20, 2, 16, 53, 23780))),
                ('asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
        ),
    ]
