# Generated by Django 5.1.5 on 2025-01-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculo_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='asignado',
        ),
    ]
