# Generated by Django 5.2 on 2025-07-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_alter_vehiculo_anio_alter_vehiculo_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['placa'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inoperativo', 'Inoperativo'), ('Mantenimiento', 'Mantenimiento')], default='Activo', max_length=30, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Pick-up', 'Pick-up'), ('Motocicleta', 'Motocicleta'), ('Blindado', 'Blindado'), ('Porta tropas', 'Porta tropas'), ('Vehículos de rescate', 'Vehículos de rescate'), ('Especiales', 'Especiales')], default='Sedan', max_length=30, verbose_name='Tipo'),
        ),
    ]
