# Generated by Django 5.2 on 2025-07-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0005_alter_vehiculo_options_vehiculo_estado_vehiculo_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['created'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
    ]
