# Generated by Django 5.2 on 2025-07-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0006_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de adquisición'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diésel', 'Diésel'), ('GLP', 'GLP'), ('GNV', 'GNV')], default='Gasolina', max_length=20, verbose_name='Tipo de Combustible'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='vin',
            field=models.CharField(default=1, max_length=25, verbose_name='VIN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=6, unique=True, verbose_name='Placa'),
        ),
    ]
