# Generated by Django 5.2 on 2025-08-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0008_alter_vehiculo_fecha_adquisicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='placa',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='estado_odo',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INOPERATIVO', 'INOPERATIVO'), ('MANTENIMIENTO', 'MANTENIMIENTO')], default='ACTIVO', max_length=30, verbose_name='Estado del odometro'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='estado_vehi',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INOPERATIVO', 'INOPERATIVO'), ('Mantenimiento', 'Mantenimiento')], default='ACTIVO', max_length=30, verbose_name='Estado del vehículo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_fabricacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fabricación'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='funcion',
            field=models.CharField(choices=[('ADMINISTRATIVO', 'ADMINISTRATIVO'), ('OPERATIVO', 'OPERATIVO'), ('PATRULLAJE', 'PATRULLAJE'), ('ASIG. AL CARGO', 'ADMASIG. AL CARGO')], default='ACTIVO', max_length=30, verbose_name='Función policial'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='num_motor',
            field=models.CharField(default=1, max_length=25, verbose_name='N° de motor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='placa_int',
            field=models.CharField(default=0, max_length=6, unique=True, verbose_name='Placa Interna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='placa_rod',
            field=models.CharField(default=1, max_length=6, unique=True, verbose_name='Placa Rodaje'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='valor',
            field=models.PositiveIntegerField(default=1, verbose_name='Valor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('AMBULANCIA', 'AMBULANCIA'), ('AUTOMOVIL', 'AUTOMOVIL'), ('AUTOMOVIL SEDAN', 'AUTOMOVIL SEDAN'), ('CAMION BARANDA', 'CAMION BARANDA'), ('CAMIONETA  FUNERARIO', 'CAMIONETA  FUNERARIO'), ('CAMIONETA  PANEL', 'CAMIONETA  PANEL'), ('CAMIONETA  PICK UP', 'CAMIONETA  PICK UP'), ('CAMIONETA  SUV', 'CAMIONETA  SUV'), ('MINIBUS', 'MINIBUS'), ('MICROBUS', 'MICROBUS'), ('MOTO ACUATICA', 'MOTO ACUATICA'), ('MOTOCICLETA', 'MOTOCICLETA'), ('MOTOR FUERA DE BORDA ', 'MOTOR FUERA DE BORDA '), ('OMNIBUS', 'OMNIBUS'), ('PORTATROPA', 'PORTATROPA'), ('STATION WAGON', 'STATION WAGON'), ('TRIMOTO', 'TRIMOTO')], default='Sedan', max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(choices=[('GASOLINA', 'GASOLINA'), ('DIESEL', 'DIESEL'), ('GLP', 'GLP'), ('GNV', 'GNV')], default='Gasolina', max_length=20, verbose_name='Tipo de Combustible'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='vin',
            field=models.CharField(max_length=20, unique=True, verbose_name='N° de serie'),
        ),
    ]
