# Generated by Django 5.2 on 2025-08-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0009_remove_vehiculo_estado_remove_vehiculo_placa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='fecha_fabricacion',
        ),
    ]
