# Generated by Django 5.2 on 2025-08-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0010_remove_vehiculo_fecha_fabricacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado_odo',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INOPERATIVO', 'INOPERATIVO')], default='ACTIVO', max_length=30, verbose_name='Estado del odometro'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado_vehi',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INOPERATIVO', 'INOPERATIVO'), ('MANTENIMIENTO', 'MANTENIMIENTO')], default='ACTIVO', max_length=30, verbose_name='Estado del vehículo'),
        ),
    ]
