# Generated by Django 5.2 on 2025-08-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0011_alter_vehiculo_estado_odo_alter_vehiculo_estado_vehi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='valor',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Valor'),
        ),
    ]
