# Generated by Django 5.2 on 2025-08-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0012_alter_vehiculo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.DecimalField(decimal_places=1, max_digits=18, verbose_name='Kilometraje'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor'),
        ),
    ]
