# Generated by Django 5.2 on 2025-08-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0013_alter_vehiculo_kilometraje_alter_vehiculo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa_int',
            field=models.CharField(max_length=8, unique=True, verbose_name='Placa Interna'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa_rod',
            field=models.CharField(max_length=8, unique=True, verbose_name='Placa Rodaje'),
        ),
    ]
