# Generated by Django 5.2 on 2025-08-14 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0002_alter_subunidad_direccion'),
        ('vehiculo', '0014_alter_vehiculo_placa_int_alter_vehiculo_placa_rod'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='subunidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ubicacion.subunidad', verbose_name='Sub Unidad Asignada'),
            preserve_default=False,
        ),
    ]
