# Generated by Django 5.2 on 2025-08-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0015_vehiculo_subunidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado_odo',
            field=models.CharField(choices=[('OPERATIVO', 'OPERATIVO'), ('INOPERATIVO', 'INOPERATIVO')], default='OPERATIVO', max_length=30, verbose_name='Estado del odometro'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado_vehi',
            field=models.CharField(choices=[('OPERATIVO', 'OPERATIVO'), ('INOPERATIVO', 'INOPERATIVO'), ('MANTENIMIENTO', 'MANTENIMIENTO')], default='OPERATIVO', max_length=30, verbose_name='Estado del vehículo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='funcion',
            field=models.CharField(choices=[('ADMINISTRATIVO', 'ADMINISTRATIVO'), ('OPERATIVO', 'OPERATIVO'), ('PATRULLAJE', 'PATRULLAJE'), ('ASIG. AL CARGO', 'ADMASIG. AL CARGO')], default='ADMINISTRATIVO', max_length=30, verbose_name='Función policial'),
        ),
    ]
