# Generated by Django 5.2.5 on 2025-09-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0016_alter_vehiculo_estado_odo_alter_vehiculo_estado_vehi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='funcion',
            field=models.CharField(choices=[('ADMINISTRATIVO', 'ADMINISTRATIVO'), ('OPERATIVO', 'OPERATIVO'), ('PATRULLAJE', 'PATRULLAJE'), ('ASIG. AL CARGO', 'ADMASIG. AL CARGO'), ('INOPERATIVO', 'INOPERATIVO')], default='ADMINISTRATIVO', max_length=30, verbose_name='Función policial'),
        ),
    ]
