# Generated by Django 5.2.5 on 2025-09-23 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0003_alter_subunidad_telefono_contacto'),
        ('vehiculo', '0017_alter_vehiculo_funcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_ino',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inoperatividad'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='motivo_ino',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo o causa de la inoperatividad'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='procedencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Procedencia'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ubicacion_ino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_inoperativo', to='ubicacion.subunidad', verbose_name='Ubicación del vehiculo inoperativo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado_vehi',
            field=models.CharField(choices=[('OPERATIVO', 'OPERATIVO'), ('INOPERATIVO', 'INOPERATIVO'), ('RECUPERABLE', 'RECUPERABLE'), ('IRRECUPERABLE', 'IRRECUPERABLE'), ('MANTENIMIENTO', 'MANTENIMIENTO')], default='OPERATIVO', max_length=30, verbose_name='Estado del vehículo'),
        ),
    ]
