# Generated by Django 5.2.5 on 2025-09-24 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0003_alter_subunidad_telefono_contacto'),
        ('vehiculo', '0018_vehiculo_fecha_ino_vehiculo_motivo_ino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='ubicacion_ino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_inoperativo', to='ubicacion.subunidad', verbose_name='Ubicación del vehiculo inoperativo'),
        ),
    ]
