# Generated by Django 5.2.5 on 2025-09-24 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0003_alter_subunidad_telefono_contacto'),
        ('vehiculo', '0019_alter_vehiculo_ubicacion_ino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa_rod',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Placa Rodaje'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='subunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicacion.subunidad', verbose_name='Sub Unidad Asignada'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='ubicacion_ino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_inoperativo', to='ubicacion.subunidad', verbose_name='Ubicación del vehículo inoperativo'),
        ),
    ]
