# Generated by Django 5.2.5 on 2025-09-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0020_alter_vehiculo_placa_rod_alter_vehiculo_subunidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de la Baja'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='resolucion_baja',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Resolución de la Baja'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='funcion',
            field=models.CharField(choices=[('ADMINISTRATIVO', 'ADMINISTRATIVO'), ('OPERATIVO', 'OPERATIVO'), ('PATRULLAJE', 'PATRULLAJE'), ('ASIG. AL CARGO', 'ADMASIG. AL CARGO'), ('INOPERATIVO', 'INOPERATIVO')], default='', max_length=30, verbose_name='Función policial'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('AMBULANCIA', 'AMBULANCIA'), ('AUTOMOVIL', 'AUTOMOVIL'), ('AUTOMOVIL SEDAN', 'AUTOMOVIL SEDAN'), ('CAMION BARANDA', 'CAMION BARANDA'), ('CAMIONETA  FUNERARIO', 'CAMIONETA  FUNERARIO'), ('CAMIONETA  PANEL', 'CAMIONETA  PANEL'), ('CAMIONETA  PICK UP', 'CAMIONETA  PICK UP'), ('CAMIONETA  SUV', 'CAMIONETA  SUV'), ('MINIBUS', 'MINIBUS'), ('MICROBUS', 'MICROBUS'), ('MOTO ACUATICA', 'MOTO ACUATICA'), ('MOTOCICLETA', 'MOTOCICLETA'), ('MOTOR FUERA DE BORDA ', 'MOTOR FUERA DE BORDA '), ('OMNIBUS', 'OMNIBUS'), ('PORTATROPA', 'PORTATROPA'), ('STATION WAGON', 'STATION WAGON'), ('TRIMOTO', 'TRIMOTO')], default='', max_length=30, verbose_name='Tipo'),
        ),
    ]
