# Generated by Django 5.2.5 on 2025-09-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0021_vehiculo_fecha_baja_vehiculo_resolucion_baja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado_vehi',
            field=models.CharField(choices=[('OPERATIVO', 'OPERATIVO'), ('INOPERATIVO', 'INOPERATIVO'), ('INOP. IRRECUP.', 'INOP. IRRECUP.'), ('INOP. RECUP.', 'INOP. RECUP.'), ('RECUPERABLE', 'RECUPERABLE'), ('IRRECUPERABLE', 'IRRECUPERABLE'), ('MANTENIMIENTO', 'MANTENIMIENTO')], default='OPERATIVO', max_length=30, verbose_name='Estado del vehículo'),
        ),
    ]
