# Generated by Django 5.2.5 on 2025-09-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0022_alter_vehiculo_estado_vehi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa_int',
            field=models.CharField(max_length=10, unique=True, verbose_name='Placa Interna'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa_rod',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Placa Rodaje'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('AMBULANCIA', 'AMBULANCIA'), ('AUTOMOVIL', 'AUTOMOVIL'), ('AUTOMOVIL SEDAN', 'AUTOMOVIL SEDAN'), ('BOTE', 'BOTE'), ('CAMION BARANDA', 'CAMION BARANDA'), ('CAMIONETA', 'CAMIONETA'), ('CAMIONETA FUNERARIO', 'CAMIONETA FUNERARIO'), ('CAMIONETA PANEL', 'CAMIONETA PANEL'), ('CAMIONETA PICK UP', 'CAMIONETA PICK UP'), ('CAMIONETA SUV', 'CAMIONETA SUV'), ('MINIBUS', 'MINIBUS'), ('MICROBUS', 'MICROBUS'), ('MOTO ACUATICA', 'MOTO ACUATICA'), ('MOTOCICLETA', 'MOTOCICLETA'), ('MOTOR FUERA DE BORDA ', 'MOTOR FUERA DE BORDA '), ('OMNIBUS', 'OMNIBUS'), ('PORTATROPA', 'PORTATROPA'), ('STATION WAGON', 'STATION WAGON'), ('TRIMOTO', 'TRIMOTO')], default='', max_length=30, verbose_name='Tipo'),
        ),
    ]
