# Generated by Django 5.2.5 on 2025-09-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0023_alter_vehiculo_placa_int_alter_vehiculo_placa_rod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='num_motor',
            field=models.CharField(max_length=30, verbose_name='N° de motor'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='vin',
            field=models.CharField(max_length=30, unique=True, verbose_name='N° de serie'),
        ),
    ]
