# Generated by Django 5.2 on 2025-07-26 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0011_remove_persona_estecnico_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comisaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la comisaría')),
                ('direccion', models.CharField(max_length=70, verbose_name='Dirección')),
                ('telefono_contacto', models.PositiveIntegerField(blank=True, default=0, max_length=9, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
        ),
    ]
